server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-accelerate.aliyuncs.com
    keyId: LTAI5tQNXFdkFgMTEBLREyYX
    keySecret: dOp8p34Qnz2Wk1fk0j0n69QVDd1uEu
    bucketName: srb-chenfile